export const countryCode = {
  AD: 'AD',
  AE: 'AE',
  AF: 'AF',
  AG: 'AG',
  AI: 'AI',
  AL: 'AL',
  AM: 'AM',
  AO: 'AO',
  AQ: 'AQ',
  AR: 'AR',
  AS: 'AS',
  AT: 'AT',
  AU: 'AU',
  AW: 'AW',
  AX: 'AX',
  AZ: 'AZ',
  BA: 'BA',
  BB: 'BB',
  BD: 'BD',
  BE: 'BE',
  BF: 'BF',
  BG: 'BG',
  BH: 'BH',
  BI: 'BI',
  BJ: 'BJ',
  BL: 'BL',
  BM: 'BM',
  BN: 'BN',
  BO: 'BO',
  BQ: 'BQ',
  BR: 'BR',
  BS: 'BS',
  BT: 'BT',
  BV: 'BV',
  BW: 'BW',
  BY: 'BY',
  BZ: 'BZ',
  CA: 'CA',
  CC: 'CC',
  CD: 'CD',
  CF: 'CF',
  CG: 'CG',
  CH: 'CH',
  CI: 'CI',
  CK: 'CK',
  CL: 'CL',
  CM: 'CM',
  CN: 'CN',
  CO: 'CO',
  CR: 'CR',
  CU: 'CU',
  CV: 'CV',
  CW: 'CW',
  CX: 'CX',
  CY: 'CY',
  CZ: 'CZ',
  DE: 'DE',
  DJ: 'DJ',
  DK: 'DK',
  DM: 'DM',
  DO: 'DO',
  DZ: 'DZ',
  EC: 'EC',
  EE: 'EE',
  EG: 'EG',
  EH: 'EH',
  ER: 'ER',
  ES: 'ES',
  ET: 'ET',
  FI: 'FI',
  FJ: 'FJ',
  FK: 'FK',
  FM: 'FM',
  FO: 'FO',
  FR: 'FR',
  GA: 'GA',
  GB: 'GB',
  GD: 'GD',
  GE: 'GE',
  GF: 'GF',
  GG: 'GG',
  GH: 'GH',
  GI: 'GI',
  GL: 'GL',
  GM: 'GM',
  GN: 'GN',
  GP: 'GP',
  GQ: 'GQ',
  GR: 'GR',
  GS: 'GS',
  GT: 'GT',
  GU: 'GU',
  GW: 'GW',
  GY: 'GY',
  HK: 'HK',
  HM: 'HM',
  HN: 'HN',
  HR: 'HR',
  HT: 'HT',
  HU: 'HU',
  ID: 'ID',
  IE: 'IE',
  IL: 'IL',
  IM: 'IM',
  IN: 'IN',
  IO: 'IO',
  IQ: 'IQ',
  IR: 'IR',
  IS: 'IS',
  IT: 'IT',
  JE: 'JE',
  JM: 'JM',
  JO: 'JO',
  JP: 'JP',
  KE: 'KE',
  KG: 'KG',
  KH: 'KH',
  KI: 'KI',
  KM: 'KM',
  KN: 'KN',
  KP: 'KP',
  KR: 'KR',
  KW: 'KW',
  KY: 'KY',
  KZ: 'KZ',
  LA: 'LA',
  LB: 'LB',
  LC: 'LC',
  LI: 'LI',
  LK: 'LK',
  LR: 'LR',
  LS: 'LS',
  LT: 'LT',
  LU: 'LU',
  LV: 'LV',
  LY: 'LY',
  MA: 'MA',
  MC: 'MC',
  MD: 'MD',
  ME: 'ME',
  MF: 'MF',
  MG: 'MG',
  MH: 'MH',
  MK: 'MK',
  ML: 'ML',
  MM: 'MM',
  MN: 'MN',
  MO: 'MO',
  MP: 'MP',
  MQ: 'MQ',
  MR: 'MR',
  MS: 'MS',
  MT: 'MT',
  MU: 'MU',
  MV: 'MV',
  MW: 'MW',
  MX: 'MX',
  MY: 'MY',
  MZ: 'MZ',
  NA: 'NA',
  NC: 'NC',
  NE: 'NE',
  NF: 'NF',
  NG: 'NG',
  NI: 'NI',
  NL: 'NL',
  NO: 'NO',
  NP: 'NP',
  NR: 'NR',
  NU: 'NU',
  NZ: 'NZ',
  OM: 'OM',
  PA: 'PA',
  PE: 'PE',
  PF: 'PF',
  PG: 'PG',
  PH: 'PH',
  PK: 'PK',
  PL: 'PL',
  PM: 'PM',
  PN: 'PN',
  PR: 'PR',
  PS: 'PS',
  PT: 'PT',
  PW: 'PW',
  PY: 'PY',
  QA: 'QA',
  RE: 'RE',
  RO: 'RO',
  RS: 'RS',
  RU: 'RU',
  RW: 'RW',
  SA: 'SA',
  SB: 'SB',
  SC: 'SC',
  SD: 'SD',
  SE: 'SE',
  SG: 'SG',
  SH: 'SH',
  SI: 'SI',
  SJ: 'SJ',
  SK: 'SK',
  SL: 'SL',
  SM: 'SM',
  SN: 'SN',
  SO: 'SO',
  SR: 'SR',
  SS: 'SS',
  ST: 'ST',
  SV: 'SV',
  SX: 'SX',
  SY: 'SY',
  SZ: 'SZ',
  TC: 'TC',
  TD: 'TD',
  TF: 'TF',
  TG: 'TG',
  TH: 'TH',
  TJ: 'TJ',
  TK: 'TK',
  TL: 'TL',
  TM: 'TM',
  TN: 'TN',
  TO: 'TO',
  TR: 'TR',
  TT: 'TT',
  TV: 'TV',
  TW: 'TW',
  TZ: 'TZ',
  UA: 'UA',
  UG: 'UG',
  UM: 'UM',
  US: 'US',
  UY: 'UY',
  UZ: 'UZ',
  VA: 'VA',
  VC: 'VC',
  VE: 'VE',
  VG: 'VG',
  VI: 'VI',
  VN: 'VN',
  VU: 'VU',
  WF: 'WF',
  WS: 'WS',
  YE: 'YE',
  YT: 'YT',
  ZA: 'ZA',
  ZM: 'ZM',
  ZW: 'ZW',
} as const;

export const countryCodeNameMapping: Record<
  (typeof countryCode)[keyof typeof countryCode],
  string
> = {
  [countryCode.AD]: 'Andorra',
  [countryCode.AE]: 'United Arab Emirates',
  [countryCode.AF]: 'Afghanistan',
  [countryCode.AG]: 'Antigua and Barbuda',
  [countryCode.AI]: 'Anguilla',
  [countryCode.AL]: 'Albania',
  [countryCode.AM]: 'Armenia',
  [countryCode.AO]: 'Angola',
  [countryCode.AQ]: 'Antarctica',
  [countryCode.AR]: 'Argentina',
  [countryCode.AS]: 'American Samoa',
  [countryCode.AT]: 'Austria',
  [countryCode.AU]: 'Australia',
  [countryCode.AW]: 'Aruba',
  [countryCode.AX]: 'Åland Islands',
  [countryCode.AZ]: 'Azerbaijan',
  [countryCode.BA]: 'Bosnia and Herzegovina',
  [countryCode.BB]: 'Barbados',
  [countryCode.BD]: 'Bangladesh',
  [countryCode.BE]: 'Belgium',
  [countryCode.BF]: 'Burkina Faso',
  [countryCode.BG]: 'Bulgaria',
  [countryCode.BH]: 'Bahrain',
  [countryCode.BI]: 'Burundi',
  [countryCode.BJ]: 'Benin',
  [countryCode.BL]: 'Saint Barthélemy',
  [countryCode.BM]: 'Bermuda',
  [countryCode.BN]: 'Brunei Darussalam',
  [countryCode.BO]: 'Bolivia (Plurinational State of)',
  [countryCode.BQ]: 'Caribbean Netherlands',
  [countryCode.BR]: 'Brazil',
  [countryCode.BS]: 'The Bahamas',
  [countryCode.BT]: 'Bhutan',
  [countryCode.BV]: 'Bouvet Island',
  [countryCode.BW]: 'Botswana',
  [countryCode.BY]: 'Belarus',
  [countryCode.BZ]: 'Belize',
  [countryCode.CA]: 'Canada',
  [countryCode.CC]: 'Cocos (Keeling) Islands',
  [countryCode.CD]: 'Democratic Republic of the Congo',
  [countryCode.CF]: 'Central African Republic',
  [countryCode.CG]: 'Republic of the Congo',
  [countryCode.CH]: 'Switzerland',
  [countryCode.CI]: "Côte d'Ivoire",
  [countryCode.CK]: 'Cook Islands',
  [countryCode.CL]: 'Chile',
  [countryCode.CM]: 'Cameroon',
  [countryCode.CN]: 'China',
  [countryCode.CO]: 'Colombia',
  [countryCode.CR]: 'Costa Rica',
  [countryCode.CU]: 'Cuba',
  [countryCode.CV]: 'Cabo Verde',
  [countryCode.CW]: 'Curaçao',
  [countryCode.CX]: 'Christmas Island',
  [countryCode.CY]: 'Cyprus',
  [countryCode.CZ]: 'Czech Republic',
  [countryCode.DE]: 'Germany',
  [countryCode.DJ]: 'Djibouti',
  [countryCode.DK]: 'Denmark',
  [countryCode.DM]: 'Dominica',
  [countryCode.DO]: 'Dominican Republic',
  [countryCode.DZ]: 'Algeria',
  [countryCode.EC]: 'Ecuador',
  [countryCode.EE]: 'Estonia',
  [countryCode.EG]: 'Egypt',
  [countryCode.EH]: 'Western Sahara',
  [countryCode.ER]: 'Eritrea',
  [countryCode.ES]: 'Spain',
  [countryCode.ET]: 'Ethiopia',
  [countryCode.FI]: 'Finland',
  [countryCode.FJ]: 'Fiji',
  [countryCode.FK]: 'Falkland Islands (Malvinas)',
  [countryCode.FM]: 'Federated States of Micronesia',
  [countryCode.FO]: 'Faroe Islands',
  [countryCode.FR]: 'France',
  [countryCode.GA]: 'Gabon',
  [countryCode.GB]: 'United Kingdom',
  [countryCode.GD]: 'Grenada',
  [countryCode.GE]: 'Georgia',
  [countryCode.GF]: 'French Guiana',
  [countryCode.GG]: 'Guernsey',
  [countryCode.GH]: 'Ghana',
  [countryCode.GI]: 'Gibraltar',
  [countryCode.GL]: 'Greenland',
  [countryCode.GM]: 'The Gambia',
  [countryCode.GN]: 'Guinea',
  [countryCode.GP]: 'Guadeloupe',
  [countryCode.GQ]: 'Equatorial Guinea',
  [countryCode.GR]: 'Greece',
  [countryCode.GS]: 'South Georgia and the South Sandwich Islands',
  [countryCode.GT]: 'Guatemala',
  [countryCode.GU]: 'Guam',
  [countryCode.GW]: 'Guinea-Bissau',
  [countryCode.GY]: 'Guyana',
  [countryCode.HK]: 'Hong Kong',
  [countryCode.HM]: 'Heard Island and McDonald Islands',
  [countryCode.HN]: 'Honduras',
  [countryCode.HR]: 'Croatia',
  [countryCode.HT]: 'Haiti',
  [countryCode.HU]: 'Hungary',
  [countryCode.ID]: 'Indonesia',
  [countryCode.IE]: 'Ireland',
  [countryCode.IL]: 'Israel',
  [countryCode.IM]: 'Isle of Man',
  [countryCode.IN]: 'India',
  [countryCode.IO]: 'British Indian Ocean Territory',
  [countryCode.IQ]: 'Iraq',
  [countryCode.IR]: 'Iran (Islamic Republic of)',
  [countryCode.IS]: 'Iceland',
  [countryCode.IT]: 'Italy',
  [countryCode.JE]: 'Jersey',
  [countryCode.JM]: 'Jamaica',
  [countryCode.JO]: 'Jordan',
  [countryCode.JP]: 'Japan',
  [countryCode.KE]: 'Kenya',
  [countryCode.KG]: 'Kyrgyzstan',
  [countryCode.KH]: 'Cambodia',
  [countryCode.KI]: 'Kiribati',
  [countryCode.KM]: 'Comoros',
  [countryCode.KN]: 'Saint Kitts and Nevis',
  [countryCode.KP]: 'North Korea',
  [countryCode.KR]: 'South Korea',
  [countryCode.KW]: 'Kuwait',
  [countryCode.KY]: 'Cayman Islands',
  [countryCode.KZ]: 'Kazakhstan',
  [countryCode.LA]: 'Laos',
  [countryCode.LB]: 'Lebanon',
  [countryCode.LC]: 'Saint Lucia',
  [countryCode.LI]: 'Liechtenstein',
  [countryCode.LK]: 'Sri Lanka',
  [countryCode.LR]: 'Liberia',
  [countryCode.LS]: 'Lesotho',
  [countryCode.LT]: 'Lithuania',
  [countryCode.LU]: 'Luxembourg',
  [countryCode.LV]: 'Latvia',
  [countryCode.LY]: 'Libya',
  [countryCode.MA]: 'Morocco',
  [countryCode.MC]: 'Monaco',
  [countryCode.MD]: 'Moldova',
  [countryCode.ME]: 'Montenegro',
  [countryCode.MF]: 'Saint-Martin',
  [countryCode.MG]: 'Madagascar',
  [countryCode.MH]: 'Marshall Islands',
  [countryCode.MK]: 'North Macedonia',
  [countryCode.ML]: 'Mali',
  [countryCode.MM]: 'Myanmar',
  [countryCode.MN]: 'Mongolia',
  [countryCode.MO]: 'Macau',
  [countryCode.MP]: 'Northern Mariana Islands',
  [countryCode.MQ]: 'Martinique',
  [countryCode.MR]: 'Mauritania',
  [countryCode.MS]: 'Montserrat',
  [countryCode.MT]: 'Malta',
  [countryCode.MU]: 'Mauritius',
  [countryCode.MV]: 'Maldives',
  [countryCode.MW]: 'Malawi',
  [countryCode.MX]: 'Mexico',
  [countryCode.MY]: 'Malaysia',
  [countryCode.MZ]: 'Mozambique',
  [countryCode.NA]: 'Namibia',
  [countryCode.NC]: 'New Caledonia',
  [countryCode.NE]: 'Niger',
  [countryCode.NF]: 'Norfolk Island',
  [countryCode.NG]: 'Nigeria',
  [countryCode.NI]: 'Nicaragua',
  [countryCode.NL]: 'Netherlands',
  [countryCode.NO]: 'Norway',
  [countryCode.NP]: 'Nepal',
  [countryCode.NR]: 'Nauru',
  [countryCode.NU]: 'Niue',
  [countryCode.NZ]: 'New Zealand',
  [countryCode.OM]: 'Oman',
  [countryCode.PA]: 'Panama',
  [countryCode.PE]: 'Peru',
  [countryCode.PF]: 'French Polynesia',
  [countryCode.PG]: 'Papua New Guinea',
  [countryCode.PH]: 'Philippines',
  [countryCode.PK]: 'Pakistan',
  [countryCode.PL]: 'Poland',
  [countryCode.PM]: 'Saint-Pierre and Miquelon',
  [countryCode.PN]: 'Pitcairn Islands',
  [countryCode.PR]: 'Puerto Rico',
  [countryCode.PS]: 'State of Palestine',
  [countryCode.PT]: 'Portugal',
  [countryCode.PW]: 'Palau',
  [countryCode.PY]: 'Paraguay',
  [countryCode.QA]: 'Qatar',
  [countryCode.RE]: 'Réunion',
  [countryCode.RO]: 'Romania',
  [countryCode.RS]: 'Serbia',
  [countryCode.RU]: 'Russia',
  [countryCode.RW]: 'Rwanda',
  [countryCode.SA]: 'Saudi Arabia',
  [countryCode.SB]: 'Solomon Islands',
  [countryCode.SC]: 'Seychelles',
  [countryCode.SD]: 'Sudan',
  [countryCode.SE]: 'Sweden',
  [countryCode.SG]: 'Singapore',
  [countryCode.SH]: 'Saint Helena, Ascension and Tristan da Cunha',
  [countryCode.SI]: 'Slovenia',
  [countryCode.SJ]: 'Svalbard and Jan Mayen',
  [countryCode.SK]: 'Slovakia',
  [countryCode.SL]: 'Sierra Leone',
  [countryCode.SM]: 'San Marino',
  [countryCode.SN]: 'Senegal',
  [countryCode.SO]: 'Somalia',
  [countryCode.SR]: 'Suriname',
  [countryCode.SS]: 'South Sudan',
  [countryCode.ST]: 'São Tomé and Príncipe',
  [countryCode.SV]: 'El Salvador',
  [countryCode.SX]: 'Sint Maarten',
  [countryCode.SY]: 'Syria',
  [countryCode.SZ]: 'Eswatini',
  [countryCode.TC]: 'Turks and Caicos Islands',
  [countryCode.TD]: 'Chad',
  [countryCode.TF]: 'French Southern Territories',
  [countryCode.TG]: 'Togo',
  [countryCode.TH]: 'Thailand',
  [countryCode.TJ]: 'Tajikistan',
  [countryCode.TK]: 'Tokelau',
  [countryCode.TL]: 'Timor-Leste',
  [countryCode.TM]: 'Turkmenistan',
  [countryCode.TN]: 'Tunisia',
  [countryCode.TO]: 'Tonga',
  [countryCode.TR]: 'Turkey',
  [countryCode.TT]: 'Trinidad and Tobago',
  [countryCode.TV]: 'Tuvalu',
  [countryCode.TW]: 'Taiwan',
  [countryCode.TZ]: 'Tanzania',
  [countryCode.UA]: 'Ukraine',
  [countryCode.UG]: 'Uganda',
  [countryCode.UM]: 'United States Minor Outlying Islands',
  [countryCode.US]: 'United States',
  [countryCode.UY]: 'Uruguay',
  [countryCode.UZ]: 'Uzbekistan',
  [countryCode.VA]: 'Vatican City',
  [countryCode.VC]: 'Saint Vincent and the Grenadines',
  [countryCode.VE]: 'Venezuela',
  [countryCode.VG]: 'British Virgin Islands',
  [countryCode.VI]: 'United States Virgin Islands',
  [countryCode.VN]: 'Vietnam',
  [countryCode.VU]: 'Vanuatu',
  [countryCode.WF]: 'Wallis and Futuna',
  [countryCode.WS]: 'Samoa',
  [countryCode.YE]: 'Yemen',
  [countryCode.YT]: 'Mayotte',
  [countryCode.ZA]: 'South Africa',
  [countryCode.ZM]: 'Zambia',
  [countryCode.ZW]: 'Zimbabwe',
};
